code/src/Django/scode/judge/urls.py
from django.conf.urls import url
from django.contrib import admin
from judge.views import *

urlpatterns = [
    # example : /professor
    url(r'^professor$', ProfessorMainLV.as_view(), name='professor'),

    # example : /professor/python_01
    url(r'^professor/subject$', ProfessorSubjectLV.as_view(), name='subject'),

    # example : /professor/python_01/add
    url(r'^professor/subject/add$', ProfessorCreateView.as_view(), name='add'),

    # example : /professor/python_01/update
    url(r'^professor/subject/update$', ProfessorUpdateView.as_view(), name='update'),

    # example : /professor/python_01/delete
    url(r'^professor/subject/delete$', ProfessorDeleteView.as_view(), name='delete'),

    # example : /professor/python_01/settings
    url(r'^professor/subject/settings$', ProfessorSettingsView.as_view(), name='settings'),

    # example : /professor/python_01/3
    url(r'^professor/subject/result$', ProfessorResultLV.as_view(), name='result'),



    # example : /student
    url(r'^student/$', StudentMainLV.as_view(), name='student'),

    # example : /student/python_01
    url(r'^student/std_subject$', StudentSubjectLV.as_view(), name='std_subject'),

    # example : /student/python_01/3
    url(r'^student/std_assign$', Coding, name='std_assign'),
]

code/src/Django/scode/scode/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from scode.views import HomeView

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^judge/', include(('judge.urls', 'judge'), namespace='judge')),

    url(r'^$', HomeView.as_view(), name='home'),
]

code/src/Django/scode/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
<title>{% block title %}Django Web Programming{% endblock %}</title>

{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static "css/base.css" %}" />
<link rel="stylesheet" type="text/css" href="{% block extrastyle %}{% endblock %}" />

</head>

<body>
<div id="header">
	<h2 class="logo">
		<a href="{% url 'home' %}"><img src="{% static 'img/hallym_logo.png' %}" style="height:30px;"/></a></h2>
	<h2 class="maintitle"><a href="{% url 'home' %}">Scode</a></h2>
	{% if user.is_active %}
	<h4 class="welcome">Welcome, 

		<strong>{% firstof user.get_short_name user.get_username %}</strong> /
		<a href="#">Change Password</a> /
		<a href="#">Logout</a>
	</h4>
	{% else %}
	<h4 class="welcome">Welcome, Anonymous /
		<a href="#">Login</a>
	</h4>
	{% endif %}
</div>

<div id="menu">
	<li><a href="{% url 'judge:professor' %}">Professor</a>
		<ul style="width:322px;">
			<li><a href="{% url 'judge:subject' %}">Subject</a></li>
			<li><a href="{% url 'judge:add' %}">Add</a></li>
			<li><a href="{% url 'judge:update' %}">Update</a></li>
			<li><a href="{% url 'judge:delete' %}">Delete</a></li>
			<li><a href="{% url 'judge:settings' %}">Settings</a></li>
			<li><a href="{% url 'judge:result' %}">Result</a></li>
		</ul>
	</li>
	<li><a href="{% url 'judge:student' %}">Student</a>
		<ul style="width:322px;">
			<li><a href="{% url 'judge:student' %}">Student</a></li>
			<li><a href="{% url 'judge:std_subject' %}">Std_subject</a></li>
			<li><a href="{% url 'judge:std_assign' %}">Std_assign</a></li>
		</ul>
	</li>
</div>

{% block content %}{% endblock %}
{% block footer %}
<div id="footer">
	&copy; scode team
	&nbsp; &nbsp; &nbsp; &nbsp;
	<a href="https://github.com/BJ-Lim/Capstone_Design">Our git</a>
	&nbsp; &nbsp; &nbsp; &nbsp;
	<a href="https://github.com/DMOJ">Dmoj-project</a>
</div>
{% endblock footer %}
</body>
</html>

code/src/Django/scode/templates/home.html
{% extends "base.html" %}

{% block title %}home.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/home.css" %}{% endblock %}

{% block content %}

<div id="content_home">
	<div id="homeimg">
		<a href="/"><img src="{% static 'img/hallym_logo.png' %}" style="height:256px;"/></a>
		<h4 style="margin: 0;">This is Test Home Page.</h4>
	</div>

	<hr style="margin: 5px 0;">

</div>
{% endblock content %}